# Proyecto Curso Intermedio de Analítica Avanzada

En este archivo se encuentran las pruebas realizadas para validar los modelos con sus parámetros optimizados. Este repositorio ha sido elaborado para poder analizar ciertas problemáticas de la NBA con modelos de machine learning y deep learning. Los autores de este proyecto son:

- Luis Alberto Arias Llaguno
- David Ceballos Mata
- Rubén Octavio Flores Ramos

En este archivo se verá problema por problema los resultados obtenidos para validar los modelos con sus parámetros optimizados. Asimismo, se verá la exploración de datos y la limpieza de datos de la api de la NBA para poder obtener los datos necesarios para los modelos.

# 0. Importación de librerías

In [1]:
# Instalación de librerías

%pip install nba_api
%pip install tensorflow
%pip install keras
%pip install keras_tuner

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nba_api in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nba_api) (1.26.4)
Requirement already satisfied: pandas>=2.2.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from nba_api) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=2.2.0->nba_api) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas>=2.2.0->nba_api) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: tensorflow in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (6.31.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (4.14.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (3.12.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.6.15)
Requirement already satisfied: markdown>=2.6.8 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10)
Requirement already satisfied: pillow in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorboard~=2.20.0->tensorflow) (11.2.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tensorboard~=2.20.0->tensorflow) (2.3.7)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras>=3.10.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras>=3.10.0->tensorflow) (0.18.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras>=3.10.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keras in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.12.0)
Requirement already satisfied: absl-py in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (2.3.1)
Requirement already satisfied: numpy in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (1.26.4)
Requirement already satisfied: rich in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (14.2.0)
Requirement already satisfied: namex in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (3.15.1)
Requirement already satisfied: optree in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (0.18.0)
Requirement already satisfied: ml-dtypes in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (0.5.4)
Requirement already satisfied: packaging in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras) (25.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optree->keras) (4.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keras_tuner in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.4.8)
Requirement already satisfied: keras in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (3.12.0)
Requirement already satisfied: packaging in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (25.0)
Requirement already satisfied: requests in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (2.32.5)
Requirement already satisfied: kt-legacy in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (1.0.5)
Requirement already satisfied: grpcio in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (1.74.0)
Requirement already satisfied: protobuf in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras_tuner) (6.31.1)
Requirement already satisfied: absl-py in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (2.3.1)
Requirement already satisfied: numpy in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (1.26.4)
Requirement already satisfied: rich in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (14.2.0)
Requirement already satisfied: namex in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (3.15.1)
Requirement already satisfied: optree in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from keras->keras_tuner) (0.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from optree->keras->keras_tuner) (4.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->keras_tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->keras_tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->keras_tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->keras_tuner) (2025.6.15)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras->keras_tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich->keras->keras_tuner) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\luis_\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras_tuner) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importación de librerías

from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams
from nba_api.stats.static import players
from nba_api.stats.endpoints import leaguedashplayerstats

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay, silhouette_score, r2_score
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
import keras_tuner as kt

import mlflow
import mlflow.tensorflow

C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_shape.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/types.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/full_type.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/function.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/node_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/op_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph_debug_info.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/versions.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at xla/tsl/protobuf/coordination_config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/cost_graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/step_stats.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/allocation_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/cluster.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/debug.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

# 1. Exploración de datos

# 2. Problemas a Resolver

## 2.1 Predicción de rendimiento partido a partido usando LSTM (Parte 1) (Luis)

### Problema: 
Predecir la línea de puntos, de un equipo (en este caso Lakers) en su próximo partido tomando en cuenta los juegos anteriores. Para este problema, vamos a probar con los 3, 5, y 10 juegos anteriores para poder predecir los puntos de los futuros juegos de los lakers. En esta parte 1 se puede ver que solo se toman en cuenta los juegos de los Lakers como características para el modelo de redes neuronales.

### 2.1.1 Obtención y de datos

In [41]:
# Obtener el ID de los Lakers
nba_teams = teams.get_teams()
lakers = [team for team in nba_teams if team['full_name'] == 'Los Angeles Lakers'][0]
lakers_id = lakers['id']

# Usar LeagueGameFinder para obtener todos los juegos de los Lakers
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=lakers_id)
games = gamefinder.get_data_frames()[0]

# Crear DataFrame con las columnas más relevantes
df_lakers = games[[
    'SEASON_ID',           # Temporada
    'GAME_ID',             # ID del juego
    'GAME_DATE',           # Fecha del juego
    'MATCHUP',             # Matchup (LAL vs. OPP o LAL @ OPP)
    'WL',                  # Win/Loss
    'MIN',                 # Minutos jugados
    'PTS',                 # Puntos anotados
    'FGM',                 # Field Goals Made (tiros de campo anotados)
    'FGA',                 # Field Goals Attempted (tiros de campo intentados)
    'FG_PCT',              # Porcentaje de tiros de campo
    'FG3M',                # 3-Point Field Goals Made (triples anotados)
    'FG3A',                # 3-Point Field Goals Attempted (triples intentados)
    'FG3_PCT',             # Porcentaje de triples
    'FTM',                 # Free Throws Made (tiros libres anotados)
    'FTA',                 # Free Throws Attempted (tiros libres intentados)
    'FT_PCT',              # Porcentaje de tiros libres
    'OREB',                # Rebotes ofensivos
    'DREB',                # Rebotes defensivos
    'REB',                 # Rebotes totales
    'AST',                 # Asistencias
    'STL',                 # Robos
    'BLK',                 # Bloqueos
    'TOV',                 # Pérdidas de balón
    'PF',                  # Faltas personales
    'PLUS_MINUS'           # Plus/Minus
]].copy()

df_lakers.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SEASON_ID   4101 non-null   object
 1   GAME_ID     4101 non-null   object
 2   GAME_DATE   4101 non-null   object
 3   MATCHUP     4101 non-null   object
 4   WL          4099 non-null   object
 5   MIN         4101 non-null   int64
 6   PTS         4101 non-null   int64
 7   FGM         4101 non-null   int64
 8   FGA         4101 non-null   int64
 9   FG_PCT      4101 non-null   float64
 10  FG3M        4101 non-null   int64
 11  FG3A        4101 non-null   int64
 12  FG3_PCT     4089 non-null   float64
 13  FTM         4101 non-null   int64
 14  FTA         4101 non-null   int64
 15  FT_PCT      4099 non-null   float64
 16  OREB        4101 non-null   int64
 17  DREB        4101 non-null   int64
 18  REB         4101 non-null   int64
 19  AST         4101 non-null   int64
 20  STL         4101 non-null   int64
 21  BLK         4101 non-null   int64
 22  TOV         4101 non-null   int64
 23  PF          4101 non-null   int64
 24  PLUS_MINUS  2851 non-null   float64
dtypes: float64(4), int64(16), object(5)
memory usage: 801.1+ KB

### 2.1.2 Limpieza de datos

In [42]:
# Convertir la fecha a formato datetime
df_lakers['GAME_DATE'] = pd.to_datetime(df_lakers['GAME_DATE']) 

# Ordenar por fecha (más reciente primero)
df_lakers = df_lakers.sort_values('GAME_DATE', ascending=True).reset_index(drop=True) 

# Agregar columna para identificar si es juego en casa o de visitante
df_lakers['ES_CASA'] = df_lakers['MATCHUP'].str.contains('vs.').astype(int)

# Extraer el oponente
df_lakers['OPONENTE'] = df_lakers['MATCHUP'].str.split().str[-1]

# Eliminar plus_minus
df_lakers = df_lakers.drop(columns=['PLUS_MINUS']) 

# Eliminar filas con ANY valor nulo en df_lakers
df_lakers = df_lakers.dropna().reset_index(drop=True) 

# Crear columna WIN (1 para victoria, 0 para derrota)
df_lakers['WIN'] = (df_lakers['WL'] == 'W').astype(int)

# Contar los días que hubo entre juegos
df_lakers['DAYS_REST'] = df_lakers['GAME_DATE'].diff().dt.days
df_lakers['DAYS_REST'] = df_lakers['DAYS_REST'].fillna(df_lakers['DAYS_REST'].median()) # Rellenar valores nulos con la mediana
df_lakers['DAYS_REST'] = df_lakers['DAYS_REST'].astype(int)

# Visualizar los datos
pd.set_option('display.max_columns', None)
df_lakers.info()
df_lakers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4087 entries, 0 to 4086
Data columns (total 28 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SEASON_ID  4087 non-null   object
 1   GAME_ID    4087 non-null   object
 2   GAME_DATE  4087 non-null   datetime64[ns]
 3   MATCHUP    4087 non-null   object
 4   WL         4087 non-null   object
 5   MIN        4087 non-null   int64
 6   PTS        4087 non-null   int64
 7   FGM        4087 non-null   int64
 8   FGA        4087 non-null   int64
 9   FG_PCT     4087 non-null   float64
 10  FG3M       4087 non-null   int64
 11  FG3A       4087 non-null   int64
 12  FG3_PCT    4087 non-null   float64
 13  FTM        4087 non-null   int64
 14  FTA        4087 non-null   int64
 15  FT_PCT     4087 non-null   float64
 16  OREB       4087 non-null   int64
 17  DREB       4087 non-null   int64
 18  REB        4087 non-null   int64
 19  AST        4087 non-null   int64
 20  STL        4087 non-null   int64
 21  BLK        4087 non-null   int64
 22  TOV        4087 non-null   int64
 23  PF         4087 non-null   int64
 24  ES_CASA    4087 non-null   int32
 25  OPONENTE   4087 non-null   object
 26  WIN        4087 non-null   int32
 27  DAYS_REST  4087 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(3), int64(16), object(5)
memory usage: 846.3+ KB

,SEASON_ID,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,ES_CASA,OPONENTE,WIN,DAYS_REST
0,21983,0028300010,1983-10-29,LAL @ UTH,W,240,120,46,98,0.469,0,1,0.000,28,39,0.718,29,31,60,25,10,10,20,41,0,UTH,1,2
1,21983,0028300035,1983-11-02,LAL @ SDC,L,240,106,43,96,0.448,1,2,0.500,19,25,0.760,16,33,49,29,14,7,24,24,0,SDC,0,4
2,21983,0028300053,1983-11-05,LAL @ DAL,L,240,102,47,97,0.485,0,2,0.000,8,12,0.667,18,23,41,29,7,8,20,27,0,DAL,0,3
3,21983,0028300066,1983-11-08,LAL @ DEN,W,240,133,49,106,0.462,2,3,0.667,33,36,0.917,22,31,53,30,11,8,23,31,0,DEN,1,3
4,21983,0028300068,1983-11-09,LAL vs. DAL,W,240,120,50,94,0.532,2,3,0.667,18,28,0.643,16,33,49,33,7,6,17,31,1,DAL,1,1

### 2.1.3 Definición de columnas de features y target y Creación de Datasets de Entrenamiento y Validación

In [43]:
feature_cols = [
    'ES_CASA',
    'WIN',
    'MIN',
    'FGM', 'FGA', 'FG_PCT',
    'FG3M', 'FG3A', 'FG3_PCT',
    'FTM', 'FTA', 'FT_PCT',
    'OREB', 'DREB', 'REB',
    'AST', 'STL', 'BLK',
    'TOV', 'PF',
    'DAYS_REST'
]

target_col = 'PTS'

data_features = df_lakers[feature_cols].values.astype('float32')
data_target = df_lakers[target_col].values.astype('float32')

print("Features shape (sin secuencias):", data_features.shape)
print("Target shape (sin secuencias):", data_target.shape)

Features shape (sin secuencias): (4087, 21)
Target shape (sin secuencias): (4087,)

In [44]:
# Función para construir secuencias de longitud N
def build_sequences(features, target, seq_len=5):
    X, y = [], []
    n_samples = len(features)
    
    for i in range(n_samples - seq_len):
        seq_x = features[i:i+seq_len]
        seq_y = target[i+seq_len]    # Puntos del partido siguiente
        X.append(seq_x)
        y.append(seq_y)
    
    return np.array(X), np.array(y)

# Función para preparar datos para secuencias de longitud N
def prepare_data_for_seq_len(seq_len):
    X, y = build_sequences(data_features, data_target, seq_len=seq_len)
    print(f"\nSEQ_LEN = {seq_len} -> X: {X.shape}, y: {y.shape}")
    
    # split temporal 70/15/15
    n = X.shape[0]
    train_size = int(n * 0.7)
    val_size   = int(n * 0.15)
    
    X_train = X[:train_size]
    y_train = y[:train_size]
    X_val   = X[train_size:train_size+val_size]
    y_val   = y[train_size:train_size+val_size]
    X_test  = X[train_size+val_size:]
    y_test  = y[train_size+val_size:]
    
    num_features = X.shape[2]
    
    # Escalar
    X_train_2d = X_train.reshape(-1, num_features)
    X_val_2d   = X_val.reshape(-1, num_features)
    X_test_2d  = X_test.reshape(-1, num_features)
    
    scaler = StandardScaler()
    X_train_scaled_2d = scaler.fit_transform(X_train_2d)
    X_val_scaled_2d   = scaler.transform(X_val_2d)
    X_test_scaled_2d  = scaler.transform(X_test_2d)
    
    X_train_scaled = X_train_scaled_2d.reshape(X_train.shape)
    X_val_scaled   = X_val_scaled_2d.reshape(X_val.shape)
    X_test_scaled  = X_test_scaled_2d.reshape(X_test.shape)
    
    return (
        X_train_scaled, y_train,
        X_val_scaled, y_val,
        X_test_scaled, y_test,
        num_features, scaler
    )

### 2.1.4 Modelo Tuneado con Keras

In [45]:
import tensorflow as tf
from tensorflow.keras import layers, models
import keras_tuner as kt

def build_lstm_model(hp, seq_len, num_features):
    model = tf.keras.Sequential()
    
    units = hp.Int('lstm_units', min_value=16, max_value=128, step=16)
    model.add(
        layers.LSTM(
            units,
            return_sequences=False,
            input_shape=(seq_len, num_features)
        )
    )
    
    dropout_rate = hp.Float('dropout_rate', 0.0, 0.5, step=0.1)
    model.add(layers.Dropout(dropout_rate))
    
    dense_units = hp.Int('dense_units', min_value=8, max_value=64, step=8)
    model.add(layers.Dense(dense_units, activation='relu'))
    
    model.add(layers.Dense(1, activation='linear'))
    
    optimizer_name = hp.Choice('optimizer', ['sgd', 'rmsprop', 'adam'])
    learning_rate = hp.Float(
        'learning_rate',
        min_value=1e-4,
        max_value=1e-2,
        sampling='log'
    )
    
    clipnorm = hp.Choice('clipnorm', values=[0.0, 1.0, 2.0])
    clip_value = None if clipnorm == 0.0 else clipnorm
    
    if optimizer_name == 'sgd':
        momentum = hp.Float('momentum', min_value=0.0, max_value=0.9, step=0.3)
        optimizer = tf.keras.optimizers.SGD(
            learning_rate=learning_rate,
            momentum=momentum,
            clipnorm=clip_value
        )
    elif optimizer_name == 'rmsprop':
        optimizer = tf.keras.optimizers.RMSprop(
            learning_rate=learning_rate,
            clipnorm=clip_value
        )
    else:
        optimizer = tf.keras.optimizers.Adam(
            learning_rate=learning_rate,
            clipnorm=clip_value
        )
    
    model.compile(
        optimizer=optimizer,
        loss='mse',
        metrics=['mae']
    )
    
    return model


class BatchSizeTuner(kt.Hyperband):
    """Tuner que también tunea batch_size vía hp."""
    def run_trial(self, trial, *args, **kwargs):
        hp = trial.hyperparameters
        batch_size = hp.Choice('batch_size', [16, 32, 64])
        kwargs['batch_size'] = batch_size
        return super().run_trial(trial, *args, **kwargs)

### 2.1.5 MLflow con la búsqueda de hiperparámetros óptimos

In [8]:
import os
import shutil
from pathlib import Path
import mlflow
import mlflow.tensorflow

# 1. Carpeta raíz PARA MLflow (fuera del repo)
ml_root = Path(r"C:\Downloads\mlflow_nba")

# 2. Borrar lo que hubiera antes (si quieres empezar limpio)
shutil.rmtree(ml_root, ignore_errors=True)

# 3. Crear la carpeta raíz y la subcarpeta .trash (MUY IMPORTANTE)
ml_root.mkdir(parents=True, exist_ok=True)
trash_dir = ml_root / ".trash"
trash_dir.mkdir(exist_ok=True)

print("MLflow root:", ml_root)
print("Existe root:", ml_root.exists(), " / es dir:", ml_root.is_dir())
print("Existe .trash:", trash_dir.exists(), " / es dir:", trash_dir.is_dir())

# 4. Configurar tracking_uri para que apunte ahí
tracking_uri = ml_root.as_uri()  # file:///C:/Downloads/mlflow_nba
mlflow.set_tracking_uri(tracking_uri)
print("Tracking URI actual:", mlflow.get_tracking_uri())

# 5. Crear/usar experimento y activar autolog
mlflow.set_experiment("nba_lakers_lstm")
mlflow.tensorflow.autolog(disable=True)

C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\mlflow\tracking\_tracking_service\utils.py:140: FutureWarning: Filesystem tracking backend (e.g., './mlruns') is deprecated. Please switch to a database backend (e.g., 'sqlite:///mlflow.db'). For feedback, see: https://github.com/mlflow/mlflow/issues/18534
  return FileStore(store_uri, store_uri)
2025/12/11 13:55:28 INFO mlflow.tracking.fluent: Experiment with name 'nba_lakers_lstm' does not exist. Creating a new experiment.

MLflow root: C:\Downloads\mlflow_nba
Existe root: True  / es dir: True
Existe .trash: True  / es dir: True
Tracking URI actual: file:///C:/Downloads/mlflow_nba

In [9]:
with mlflow.start_run(run_name="prueba_en_downloads"):
    mlflow.log_param("test_param", 123)
    mlflow.log_metric("test_metric", 0.99)

print("Contenido de C:\\Downloads\\mlflow_nba:", os.listdir(ml_root))
for name in os.listdir(ml_root):
    print("  ", name)

Contenido de C:\Downloads\mlflow_nba: ['.trash', '511604131770777317']
   .trash
   511604131770777317

In [10]:
from pathlib import Path
import shutil

kt_dir = Path(r"E:\001 - Portafolio Anáhuac\01 - Ingeniería en Tecnologías de la Información\4to Semestre\Analítica Avanzada\proyecto-analitica-nba") / "kt_lakers_runs"
shutil.rmtree(kt_dir, ignore_errors=True)
kt_dir.mkdir(parents=True, exist_ok=True)
base_dir = kt_dir.as_posix()

print("Keras Tuner dir:", base_dir)

Keras Tuner dir: E:/001 - Portafolio Anáhuac/01 - Ingeniería en Tecnologías de la Información/4to Semestre/Analítica Avanzada/proyecto-analitica-nba/kt_lakers_runs

In [11]:
import os
import shutil
from pathlib import Path

# Carpeta para Keras Tuner (FUERA del repo)
kt_root = Path(r"C:\Downloads\kt_lakers_lstm")

# Borramos cualquier cosa vieja
shutil.rmtree(kt_root, ignore_errors=True)

# Creamos carpeta limpia
kt_root.mkdir(parents=True, exist_ok=True)

# Usamos ruta tipo POSIX (con /) que TF maneja bien
base_dir = kt_root.as_posix()

print("Keras Tuner base_dir:", base_dir)
print("Existe:", os.path.exists(base_dir), " / es dir:", os.path.isdir(base_dir))
print("Contenido:", os.listdir(base_dir))

Keras Tuner base_dir: C:/Downloads/kt_lakers_lstm
Existe: True  / es dir: True
Contenido: []

In [12]:
seq_len_candidates = [3, 5, 10]   # SEQ_LEN (los juegos anteriores que se requieren como contexto para predecir el siguiente)
max_epochs = 40

results = []

for seq_len in seq_len_candidates:
    (
        X_train_scaled, y_train,
        X_val_scaled, y_val,
        X_test_scaled, y_test,
        num_features, scaler
    ) = prepare_data_for_seq_len(seq_len)

    with mlflow.start_run(run_name=f"tuning_seq{seq_len}"):

        mlflow.log_param("seq_len", seq_len)

        def hypermodel(hp):
            return build_lstm_model(hp, seq_len, num_features)

        tuner = BatchSizeTuner(
            hypermodel,
            objective='val_loss',
            max_epochs=max_epochs,
            factor=3,
            directory=base_dir,
            project_name=f"seq_{seq_len}",
            overwrite=True
        )

        stop_early = EarlyStopping(
            monitor='val_loss',
            patience=5,
            restore_best_weights=True
        )

        tuner.search(
            X_train_scaled, y_train,
            validation_data=(X_val_scaled, y_val),
            callbacks=[stop_early],
            verbose=1
        )

        # Mejor conjunto de hiperparámetros
        best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]
        best_trial = tuner.oracle.get_best_trials(num_trials=1)[0]
        best_val_loss = best_trial.score

        # Construir modelo ganador
        best_model = tuner.hypermodel.build(best_hp)

        history = best_model.fit(
            np.concatenate([X_train_scaled, X_val_scaled], axis=0),
            np.concatenate([y_train, y_val], axis=0),
            epochs=max_epochs,
            batch_size=best_hp.get('batch_size'),
            callbacks=[stop_early],
            verbose=0
        )

        test_loss, test_mae = best_model.evaluate(X_test_scaled, y_test, verbose=0)

        # Logear solo hiperparámetros ganadores y métricas finales
        mlflow.log_metric("best_val_loss", float(best_val_loss))
        mlflow.log_metric("test_mse", float(test_loss))
        mlflow.log_metric("test_mae", float(test_mae))

        for name, value in best_hp.values.items():
            # para evitar conflictos con nombres reservados, prefijamos
            mlflow.log_param(f"best_{name}", value)

        # Guardar en lista para imprimir resumen al final
        run_result = {
            "seq_len": seq_len,
            "best_val_loss": float(best_val_loss),
            "test_mse": float(test_loss),
            "test_mae": float(test_mae),
        }
        for name, value in best_hp.values.items():
            run_result[name] = value

        results.append(run_result)

Trial 90 Complete [00h 00m 14s]
val_loss: 184.5052490234375

Best val_loss So Far: 158.71412658691406
Total elapsed time: 00h 09m 33s

C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\callbacks\early_stopping.py:99: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae
  current = self.get_monitor_value(logs)

### 2.1.6 Métricas e Interpretación

In [13]:
def print_results_for_seq_len(results, seq_len):
    print("\n" + "="*80)
    print(f"======================= RESULTADOS COMPLETOS: SEQ_LEN = {seq_len} =======================")
    print("="*80)

    filtered = [r for r in results if r["seq_len"] == seq_len]
    if not filtered:
        print(f"No hay resultados para SEQ_LEN={seq_len}.")
        return

    r = filtered[0]

    # Métricas
    print(f"\nbest_val_loss : {r['best_val_loss']}")
    print(f"test_mse       : {r['test_mse']}")
    print(f"test_mae       : {r['test_mae']}")

    print("\nHiperparámetros ganadores:")
    for k, v in r.items():
        if k not in ["seq_len", "best_val_loss", "test_mse", "test_mae"]:
            print(f"  - {k}: {v}")

    print("="*80 + "\n")


# Imprimir resultados completos para cada SEQ_LEN
print_results_for_seq_len(results, 3)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 3 =======================
================================================================================

best_val_loss : 165.90769958496094
test_mse       : 205.82420349121094
test_mae       : 11.53972053527832

Hiperparámetros ganadores:
  - lstm_units: 16
  - dropout_rate: 0.4
  - dense_units: 8
  - optimizer: sgd
  - learning_rate: 0.0038011372648135925
  - clipnorm: 1.0
  - momentum: 0.8999999999999999
  - batch_size: 32
  - tuner/epochs: 40
  - tuner/initial_epoch: 0
  - tuner/bracket: 0
  - tuner/round: 0
================================================================================

In [14]:
print_results_for_seq_len(results, 5)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 5 =======================
================================================================================

best_val_loss : 161.1466827392578
test_mse       : 230.9376220703125
test_mae       : 12.219761848449707

Hiperparámetros ganadores:
  - lstm_units: 128
  - dropout_rate: 0.30000000000000004
  - dense_units: 16
  - optimizer: sgd
  - learning_rate: 0.0017311246306854196
  - clipnorm: 0.0
  - momentum: 0.0
  - batch_size: 64
  - tuner/epochs: 40
  - tuner/initial_epoch: 14
  - tuner/bracket: 2
  - tuner/round: 2
  - tuner/trial_id: 0064
================================================================================

In [15]:
print_results_for_seq_len(results, 10)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 10 =======================
================================================================================

best_val_loss : 158.71412658691406
test_mse       : 307.41864013671875
test_mae       : 13.860396385192871

Hiperparámetros ganadores:
  - lstm_units: 48
  - dropout_rate: 0.0
  - dense_units: 24
  - optimizer: adam
  - learning_rate: 0.00306562330900601
  - clipnorm: 1.0
  - momentum: 0.6
  - batch_size: 32
  - tuner/epochs: 40
  - tuner/initial_epoch: 14
  - tuner/bracket: 3
  - tuner/round: 3
  - tuner/trial_id: 0048
================================================================================

En este caso podemos ver que el modelo que usa los 10 juegos anteriores para predecir el siguiente juego es el que tiene mejores métricas. Esto debido a la métrica de MAE (Mean Absolute Error), la cual con su valor de 11.3334 nos dice que el modelo promedio de error es de 11.3334 puntos. En otras palabras, esto dice que el modelo está prediciendo con un error promedio de 11.3334 puntos, osea que de su predicción está en promedio 11.3334 puntos de distancia de la realidad.

In [16]:
# R^2 score

y_pred = best_model.predict(X_test_scaled).flatten()   # predicciones
r2 = r2_score(y_test, y_pred)

print("Coeficiente de determinación R²:", r2)

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
Coeficiente de determinación R²: -0.5687004327774048

In [17]:
df_lakers['PTS'].mean()

105.26620993393688

Aquí hay que hacer un detenimiento especial en la evaluación de la métrica de R², porque al ser negativo teóricamente significa que el modelo mejora que si es que simplemente sacara el promedio de los valores de la variable objetivo para los juegos anteriores y predijeramos con eso. Esto se debe a un par de factores, principalmente que el promedio de puntos de todos los juegos (que hay en nba_api) de los Lakers es de 105.26, por lo que los juegos de los lakers son bastante estables. Otro factor que tomar en cuenta es que no hay características de los contrincantes, por lo que el modelo no tiene información sobre quién es el contrincante en el juego actual y esto también llega a afectar la precisión de la predicción.

## 2.2 Predicción de rendimiento partido a partido usando LSTM (Parte 2) (Luis)

### Problema: 
Predecir la línea de puntos, de un equipo (en este caso Lakers) en su próximo partido tomando en cuenta los juegos anteriores. Para este problema, vamos a probar con los 3, 5, y 10 juegos anteriores para poder predecir los puntos de los futuros juegos de los lakers. En esta parte 2 se puede ver que no solo se toman en cuenta las características de los Lakers en ese juego, sino que también se toman en cuenta las características de los contrincantes en el mismo juego como características para el modelo de redes neuronales. En teoría, estas nuevas características beneficiarían al modelo debido a que tener las características del contrincante en ese partido también da más contexto sobre el juego y de los contrincantes como han sido en el pasado para poder predecir con mayor exactitud el rendimiento de los Lakers en el próximo partido.

### 2.2.1 Crear dataframe con stats de los contrincantes y Lakers

In [46]:
teams_df = pd.DataFrame(nba_teams)
abbr_to_id = dict(zip(teams_df["abbreviation"], teams_df["id"]))

opp_abbrevs = df_lakers["OPONENTE"].unique()
print("Oponentes únicos:", opp_abbrevs)

# ¿Qué abreviaturas NO están en los equipos oficiales?
missing = [abbr for abbr in opp_abbrevs if abbr not in abbr_to_id]
print("Abreviaturas que no están en nba_teams:", missing)

Oponentes únicos: ['UTH' 'SDC' 'DAL' 'DEN' 'PHX' 'MIL' 'CLE' 'POR' 'SEA' 'CHI' 'GOS' 'NYK'
 'SAN' 'HOU' 'KCK' 'IND' 'BOS' 'WAS' 'ATL' 'PHL' 'NJN' 'DET' 'LAC' 'SAC'
 'MIA' 'CHH' 'ORL' 'MIN' 'VAN' 'TOR' 'SAS' 'GSW' 'UTA' 'PHI' 'MEM' 'NOH'
 'CHA' 'NOK' 'BAR' 'OKC' 'BKN' 'NOP' 'MAC' 'SKT']
Abreviaturas que no están en nba_teams: ['UTH', 'SDC', 'SEA', 'GOS', 'SAN', 'KCK', 'PHL', 'NJN', 'CHH', 'VAN', 'NOH', 'NOK', 'BAR', 'MAC', 'SKT']

In [47]:
# Mapa manual de abreviaturas raras a abreviaturas oficiales de nba_api
abbr_fix_map = {
    "UTH": "UTA",  # Utah Jazz
    "SDC": "LAC",  # San Diego Clippers -> LA Clippers
    "SEA": "OKC",  # Seattle SuperSonics -> Oklahoma City Thunder
    "GOS": "GSW",  # Golden State (a veces codificado raro) -> Golden State Warriors
    "SAN": "SAS",  # San Antonio -> San Antonio Spurs
    "KCK": "SAC",  # Kansas City Kings -> Sacramento Kings
    "PHL": "PHI",  # Philadelphia (viejo código) -> Philadelphia 76ers
    "NJN": "BKN",  # New Jersey Nets -> Brooklyn Nets
    "CHH": "CHA",  # Charlotte Hornets (viejos) -> Charlotte Hornets actuales
    "VAN": "MEM",  # Vancouver Grizzlies -> Memphis Grizzlies
    "NOH": "NOP",  # New Orleans Hornets -> New Orleans Pelicans
    "NOK": "NOP",  # New Orleans/Oklahoma City Hornets -> Pelicans
}

teams_df = pd.DataFrame(nba_teams)
abbr_to_id = dict(zip(teams_df["abbreviation"], teams_df["id"]))

# Aplicar corrección directamente al dataframe de Lakers
df_lakers["OPONENTE"] = df_lakers["OPONENTE"].replace(abbr_fix_map)

# Volver a calcular oponentes únicos
opp_abbrevs = df_lakers["OPONENTE"].unique()
print("Oponentes únicos normalizados:", opp_abbrevs)

# Verificar si ya todos existen
missing = [abbr for abbr in opp_abbrevs if abbr not in abbr_to_id]
print("Abreviaturas fuera de catálogo después de normalizar:", missing)

if missing:
    print("Eliminando partidos contra equipos no-NBA:", missing)
    df_lakers = df_lakers[~df_lakers["OPONENTE"].isin(missing)].reset_index(drop=True)

Oponentes únicos normalizados: ['UTA' 'LAC' 'DAL' 'DEN' 'PHX' 'MIL' 'CLE' 'POR' 'OKC' 'CHI' 'GSW' 'NYK'
 'SAS' 'HOU' 'SAC' 'IND' 'BOS' 'WAS' 'ATL' 'PHI' 'BKN' 'DET' 'MIA' 'CHA'
 'ORL' 'MIN' 'MEM' 'TOR' 'NOP' 'BAR' 'MAC' 'SKT']
Abreviaturas fuera de catálogo después de normalizar: ['BAR', 'MAC', 'SKT']
Eliminando partidos contra equipos no-NBA: ['BAR', 'MAC', 'SKT']

In [48]:
# Esta vez pedimos TODOS los juegos donde el oponente fue LAL
opp_gamefinder = leaguegamefinder.LeagueGameFinder(
    vs_team_id_nullable=lakers_id   # <-- clave: vs_team_id, no team_id
)
df_opp_raw = opp_gamefinder.get_data_frames()[0]
print("df_opp_raw (todos los rivales vs LAL) shape:", df_opp_raw.shape)

# Nos quedamos solo con los GAME_ID que están en df_lakers (por si acaso)
df_opp_raw = df_opp_raw[df_opp_raw["GAME_ID"].isin(df_lakers["GAME_ID"])]
print("df_opp_raw filtrado shape:", df_opp_raw.shape)

# Columnas relevantes del rival (mismas métricas que Lakers)
opp_cols = [
    "GAME_ID",
    "WL",          # Win/Loss del rival
    "MIN",
    "PTS",
    "FGM", "FGA", "FG_PCT",
    "FG3M", "FG3A", "FG3_PCT",
    "FTM", "FTA", "FT_PCT",
    "OREB", "DREB", "REB",
    "AST", "STL", "BLK",
    "TOV", "PF",
]

df_opp = df_opp_raw[opp_cols].copy()

# Crear columna OPP_WIN (1 si el rival ganó, 0 si perdió)
df_opp["OPP_WIN"] = (df_opp["WL"] == "W").astype(int)
df_opp = df_opp.drop(columns=["WL"])

# Renombrar métricas del rival con prefijo OPP_
rename_map = {
    col: f"OPP_{col}" for col in df_opp.columns if col != "GAME_ID"
}
df_opp.rename(columns=rename_map, inplace=True)

print("df_opp shape (una fila por equipo-rival en cada juego):", df_opp.shape)
df_opp.head()

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [49]:
df_opp.info()
df_opp.head()

<class 'pandas.core.frame.DataFrame'>
Index: 4083 entries, 0 to 4097
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GAME_ID      4083 non-null   object
 1   OPP_MIN      4083 non-null   int64
 2   OPP_PTS      4083 non-null   int64
 3   OPP_FGM      4083 non-null   int64
 4   OPP_FGA      4083 non-null   int64
 5   OPP_FG_PCT   4083 non-null   float64
 6   OPP_FG3M     4083 non-null   int64
 7   OPP_FG3A     4083 non-null   int64
 8   OPP_FG3_PCT  4044 non-null   float64
 9   OPP_FTM      4083 non-null   int64
 10  OPP_FTA      4083 non-null   int64
 11  OPP_FT_PCT   4083 non-null   float64
 12  OPP_OREB     4083 non-null   int64
 13  OPP_DREB     4083 non-null   int64
 14  OPP_REB      4083 non-null   int64
 15  OPP_AST      4083 non-null   int64
 16  OPP_STL      4083 non-null   int64
 17  OPP_BLK      4083 non-null   int64
 18  OPP_TOV      4083 non-null   int64
 19  OPP_PF       4083 non-null   int64
 20  OPP_OPP_WIN  4083 non-null   int32
dtypes: float64(3), int32(1), int64(16), object(1)
memory usage: 685.8+ KB

,GAME_ID,OPP_MIN,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_OPP_WIN
0,0022501204,240,132,43,86,0.500,17,38,0.447,29,36,0.806,9,41,50,25,9,3,10,19,1
1,0022500362,240,108,36,102,0.353,13,36,0.361,23,26,0.885,17,37,54,21,5,4,6,17,0
2,0022500338,239,126,46,84,0.548,24,45,0.533,10,12,0.833,8,30,38,31,9,5,14,20,1
3,0022500336,240,120,44,89,0.494,15,37,0.405,17,21,0.810,14,27,41,39,9,8,15,20,0
4,0022500317,240,125,52,92,0.565,17,39,0.436,4,8,0.500,4,29,33,35,16,1,11,16,1

In [ ]:
# Dataframe combinado Lakers + Rival

df_lakers_opp = df_lakers.merge(
    df_opp,
    on="GAME_ID",
    how="left",
    validate="one_to_one"  # Si truena aquí es porque hay duplicados, se puede quitar el validate
)

print("df_lakers_opp shape:", df_lakers_opp.shape)
df_lakers_opp.head()

df_lakers_opp shape: (4083, 48)

,SEASON_ID,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,ES_CASA,OPONENTE,WIN,DAYS_REST,OPP_MIN,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_OPP_WIN
0,21983,0028300010,1983-10-29,LAL @ UTH,W,240,120,46,98,0.469,0,1,0.000,28,39,0.718,29,31,60,25,10,10,20,41,0,UTA,1,2,240,115,35,77,0.455,1,3,0.333,44,60,0.733,15,26,41,21,8,10,17,27,0
1,21983,0028300035,1983-11-02,LAL @ SDC,L,240,106,43,96,0.448,1,2,0.500,19,25,0.760,16,33,49,29,14,7,24,24,0,LAC,0,4,240,110,47,91,0.516,0,1,0.000,16,23,0.696,11,31,42,30,12,8,20,24,1
2,21983,0028300053,1983-11-05,LAL @ DAL,L,240,102,47,97,0.485,0,2,0.000,8,12,0.667,18,23,41,29,7,8,20,27,0,DAL,0,3,240,107,43,97,0.443,0,2,0.000,21,26,0.808,22,26,48,26,9,4,16,20,1
3,21983,0028300066,1983-11-08,LAL @ DEN,W,240,133,49,106,0.462,2,3,0.667,33,36,0.917,22,31,53,30,11,8,23,31,0,DEN,1,3,240,124,44,96,0.458,0,8,0.000,36,42,0.857,14,30,44,28,15,4,24,26,0
4,21983,0028300068,1983-11-09,LAL vs. DAL,W,240,120,50,94,0.532,2,3,0.667,18,28,0.643,16,33,49,33,7,6,17,31,1,DAL,1,1,240,106,34,83,0.410,0,2,0.000,38,46,0.826,13,30,43,22,7,2,18,23,0

### 2.2.2 Definir columnas de features y target y Creación de Datasets de Entrenamiento y Validación

In [50]:
feature_cols_22 = [
    # Features de los Lakers (igual que en 2.1)
    'ES_CASA',
    'WIN',
    'MIN',
    'FGM', 'FGA', 'FG_PCT',
    'FG3M', 'FG3A', 'FG3_PCT',
    'FTM', 'FTA', 'FT_PCT',
    'OREB', 'DREB', 'REB',
    'AST', 'STL', 'BLK',
    'TOV', 'PF',
    'DAYS_REST',
    
    # Features del rival (prefijo OPP_)
    'OPP_MIN',
    'OPP_PTS',
    'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
    'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT',
    'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT',
    'OPP_OREB', 'OPP_DREB', 'OPP_REB',
    'OPP_AST', 'OPP_STL', 'OPP_BLK',
    'OPP_TOV', 'OPP_PF'
]

target_col_22 = 'PTS' 

data_features_22 = df_lakers_opp[feature_cols_22].values.astype('float32')
data_target_22 = df_lakers_opp[target_col_22].values.astype('float32')

print("Features 2.2 shape (sin secuencias):", data_features_22.shape)
print("Target 2.2 shape (sin secuencias):", data_target_22.shape)

Features 2.2 shape (sin secuencias): (4083, 40)
Target 2.2 shape (sin secuencias): (4083,)

### 2.2.3 Preparación de datos secuenciales para el nuevo modelo

In [51]:
def prepare_data_for_seq_len_22(seq_len):
    X, y = build_sequences(data_features_22, data_target_22, seq_len=seq_len)
    print(f"\n[2.2] SEQ_LEN = {seq_len} -> X: {X.shape}, y: {y.shape}")
    
    n = X.shape[0]
    train_size = int(n * 0.7)
    val_size   = int(n * 0.15)
    
    X_train = X[:train_size]
    y_train = y[:train_size]
    X_val   = X[train_size:train_size+val_size]
    y_val   = y[train_size:train_size+val_size]
    X_test  = X[train_size+val_size:]
    y_test  = y[train_size+val_size:]
    
    num_features = X.shape[2]
    
    # Escalado (igual que en 2.1)
    X_train_2d = X_train.reshape(-1, num_features)
    X_val_2d   = X_val.reshape(-1, num_features)
    X_test_2d  = X_test.reshape(-1, num_features)
    
    scaler = StandardScaler()
    X_train_scaled_2d = scaler.fit_transform(X_train_2d)
    X_val_scaled_2d   = scaler.transform(X_val_2d)
    X_test_scaled_2d  = scaler.transform(X_test_2d)
    
    X_train_scaled = X_train_scaled_2d.reshape(X_train.shape)
    X_val_scaled   = X_val_scaled_2d.reshape(X_val.shape)
    X_test_scaled  = X_test_scaled_2d.reshape(X_test.shape)
    
    return (
        X_train_scaled, y_train,
        X_val_scaled, y_val,
        X_test_scaled, y_test,
        num_features, scaler
    )

### 2.2.4 Flujo de Keras Tuner y MLflow

In [26]:
mlflow.set_experiment("nba_lakers_lstm_con_rival")  # nuevo experimento para Parte 2.2

seq_len_candidates_22 = [3, 5, 10]
max_epochs_22 = 40

results_22 = []

for seq_len in seq_len_candidates_22:
    (
        X_train_scaled, y_train,
        X_val_scaled, y_val,
        X_test_scaled, y_test,
        num_features, scaler
    ) = prepare_data_for_seq_len_22(seq_len)

    with mlflow.start_run(run_name=f"tuning_seq{seq_len}_rival"):

        mlflow.log_param("seq_len", seq_len)

        def hypermodel(hp):
            return build_lstm_model(hp, seq_len, num_features)

        tuner = BatchSizeTuner(
            hypermodel,
            objective='val_loss',
            max_epochs=max_epochs_22,
            factor=3,
            directory=base_dir,
            project_name=f"seq_{seq_len}_rival",
            overwrite=True
        )

        stop_early = EarlyStopping(
            monitor='val_loss',
            patience=5,
            restore_best_weights=True
        )

        tuner.search(
            X_train_scaled, y_train,
            validation_data=(X_val_scaled, y_val),
            callbacks=[stop_early],
            verbose=1
        )

        # Mejor conjunto de hiperparámetros
        best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]
        best_trial = tuner.oracle.get_best_trials(num_trials=1)[0]
        best_val_loss = best_trial.score

        # Construir modelo ganador y reentrenar con train+val
        best_model = tuner.hypermodel.build(best_hp)

        history = best_model.fit(
            np.concatenate([X_train_scaled, X_val_scaled], axis=0),
            np.concatenate([y_train, y_val], axis=0),
            epochs=max_epochs_22,
            batch_size=best_hp.get('batch_size'),
            callbacks=[stop_early],
            verbose=0
        )

        test_loss, test_mae = best_model.evaluate(X_test_scaled, y_test, verbose=0)

        # Log en MLflow
        mlflow.log_metric("best_val_loss", float(best_val_loss))
        mlflow.log_metric("test_mse", float(test_loss))
        mlflow.log_metric("test_mae", float(test_mae))

        for name, value in best_hp.values.items():
            mlflow.log_param(f"best_{name}", value)

        run_result = {
            "seq_len": seq_len,
            "best_val_loss": float(best_val_loss),
            "test_mse": float(test_loss),
            "test_mae": float(test_mae),
        }
        for name, value in best_hp.values.items():
            run_result[name] = value

        results_22.append(run_result)

Trial 90 Complete [00h 00m 18s]
val_loss: 8832.857421875

Best val_loss So Far: 187.379638671875
Total elapsed time: 00h 15m 02s

C:\Users\luis_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\callbacks\early_stopping.py:99: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae
  current = self.get_monitor_value(logs)

### 2.2.5 Métricas y Evaluación

In [27]:
print_results_for_seq_len(results_22, 3)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 3 =======================
================================================================================

best_val_loss : 187.28448486328125
test_mse       : 252.99362182617188
test_mae       : 12.887859344482422

Hiperparámetros ganadores:
  - lstm_units: 112
  - dropout_rate: 0.30000000000000004
  - dense_units: 16
  - optimizer: sgd
  - learning_rate: 0.0003383182105335443
  - clipnorm: 0.0
  - momentum: 0.6
  - batch_size: 32
  - tuner/epochs: 40
  - tuner/initial_epoch: 0
  - tuner/bracket: 0
  - tuner/round: 0
================================================================================

In [28]:
print_results_for_seq_len(results_22, 5)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 5 =======================
================================================================================

best_val_loss : 187.4408721923828
test_mse       : 252.73110961914062
test_mae       : 12.881135940551758

Hiperparámetros ganadores:
  - lstm_units: 32
  - dropout_rate: 0.2
  - dense_units: 8
  - optimizer: sgd
  - learning_rate: 0.0012306883948819032
  - clipnorm: 0.0
  - momentum: 0.8999999999999999
  - batch_size: 64
  - tuner/epochs: 5
  - tuner/initial_epoch: 2
  - tuner/bracket: 3
  - tuner/round: 1
  - tuner/trial_id: 0017
================================================================================

In [29]:
print_results_for_seq_len(results_22, 10)

================================================================================
======================= RESULTADOS COMPLETOS: SEQ_LEN = 10 =======================
================================================================================

best_val_loss : 187.379638671875
test_mse       : 253.57949829101562
test_mae       : 12.90460205078125

Hiperparámetros ganadores:
  - lstm_units: 16
  - dropout_rate: 0.4
  - dense_units: 64
  - optimizer: sgd
  - learning_rate: 0.0005986605913831514
  - clipnorm: 0.0
  - momentum: 0.3
  - batch_size: 32
  - tuner/epochs: 40
  - tuner/initial_epoch: 14
  - tuner/bracket: 2
  - tuner/round: 2
  - tuner/trial_id: 0067
================================================================================

In [30]:
y_pred_22 = best_model.predict(X_test_scaled).flatten()
r2_22 = r2_score(y_test, y_pred_22)
print("R² (modelo con stats del rival):", r2_22)

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
R² (modelo con stats del rival): -0.3034573793411255

In [31]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Entrenamiento
y_train_pred = best_model.predict(X_train_scaled).flatten()
train_mae = mean_absolute_error(y_train, y_train_pred)
train_mse = mean_squared_error(y_train, y_train_pred)

# Validación+test (según quieras, aquí test)
y_test_pred = best_model.predict(X_test_scaled).flatten()
test_mae = mean_absolute_error(y_test, y_test_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2  = r2_score(y_test, y_test_pred)

print("MAE train :", train_mae)
print("MSE train :", train_mse)
print("MAE test  :", test_mae)
print("MSE test  :", test_mse)
print("R² test   :", test_r2)

90/90 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
MAE train : 10.787086486816406
MSE train : 185.3451385498047
MAE test  : 12.904601097106934
MSE test  : 253.57949829101562
R² test   : -0.3034573793411255

In [33]:
y_mean = np.mean(y_test)
baseline_pred = np.full_like(y_test, y_mean)

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_mse = mean_squared_error(y_test, baseline_pred)
baseline_r2  = r2_score(y_test, baseline_pred)

print("Baseline MAE:", baseline_mae)
print("Baseline MSE:", baseline_mse)
print("Baseline R² :", baseline_r2)

Baseline MAE: 10.986564636230469
Baseline MSE: 194.54376220703125
Baseline R² : 0.0

## Red Neuronal Densa (ChatGPT)

In [56]:
# Partimos de df_lakers_opp ya construido
df = df_lakers_opp.copy()

# Aseguramos orden temporal
df = df.sort_values("GAME_DATE").reset_index(drop=True)

# -----------------------------
# Rolling averages (últimos 5)
# -----------------------------
window = 5

lakers_base_cols = ["PTS", "FG_PCT", "FG3_PCT", "REB", "AST"]
opp_base_cols    = ["OPP_PTS", "OPP_FG_PCT", "OPP_FG3_PCT", "OPP_REB", "OPP_AST"]

for col in lakers_base_cols:
    df[f"LAL_{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

for col in opp_base_cols:
    df[f"{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

# -----------------------------
# Rachas de victorias (streaks)
# -----------------------------
def compute_streak(series_win):
    streaks = []
    streak = 0
    for w in series_win:
        if w == 1:
            streak += 1
        else:
            streak = 0
        streaks.append(streak)
    # shift(1) para que la racha sea "antes del partido actual"
    return pd.Series(streaks).shift(1)

# Asegúrate de que WIN y OPP_WIN son 0/1
df["LAL_WIN_STREAK"] = compute_streak(df["WIN"])
df["OPP_WIN_STREAK"] = compute_streak(df["OPP_OPP_WIN"])

# -----------------------------
# Back-to-back (descanso 0 días)
# -----------------------------
df["LAL_B2B"] = (df["DAYS_REST"] == 0).astype(int)

# -----------------------------
# Definir columnas de features y target
# -----------------------------
feature_cols_b = [
    # contexto básico
    "ES_CASA",
    "DAYS_REST",
    "LAL_B2B",
    
    # forma reciente Lakers
    f"LAL_PTS_roll{window}",
    f"LAL_FG_PCT_roll{window}",
    f"LAL_FG3_PCT_roll{window}",
    f"LAL_REB_roll{window}",
    f"LAL_AST_roll{window}",
    "LAL_WIN_STREAK",
    
    # forma reciente rival
    f"OPP_PTS_roll{window}",
    f"OPP_FG_PCT_roll{window}",
    f"OPP_FG3_PCT_roll{window}",
    f"OPP_REB_roll{window}",
    f"OPP_AST_roll{window}",
    "OPP_WIN_STREAK",
]

target_col_b = "PTS"  # puntos de Lakers en ese partido

# -----------------------------
# Aquí se crea df_model (la parte que te faltaba)
# -----------------------------
df_model = df.dropna(subset=feature_cols_b + [target_col_b]).reset_index(drop=True)

print("Shape df_model:", df_model.shape)
print("Primeras columnas de df_model:", df_model.columns.tolist())

Shape df_model: (3917, 61)
Primeras columnas de df_model: ['SEASON_ID', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'ES_CASA', 'OPONENTE', 'WIN', 'DAYS_REST', 'OPP_MIN', 'OPP_PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_OPP_WIN', 'LAL_PTS_roll5', 'LAL_FG_PCT_roll5', 'LAL_FG3_PCT_roll5', 'LAL_REB_roll5', 'LAL_AST_roll5', 'OPP_PTS_roll5', 'OPP_FG_PCT_roll5', 'OPP_FG3_PCT_roll5', 'OPP_REB_roll5', 'OPP_AST_roll5', 'LAL_WIN_STREAK', 'OPP_WIN_STREAK', 'LAL_B2B']

In [57]:
# Ya está ordenado por fecha
n = len(df_model)
train_end = int(n * 0.7)
val_end   = int(n * 0.85)

train_df = df_model.iloc[:train_end]
val_df   = df_model.iloc[train_end:val_end]
test_df  = df_model.iloc[val_end:]

X_train = train_df[feature_cols_b].values.astype("float32")
y_train = train_df[target_col_b].values.astype("float32")

X_val   = val_df[feature_cols_b].values.astype("float32")
y_val   = val_df[target_col_b].values.astype("float32")

X_test  = test_df[feature_cols_b].values.astype("float32")
y_test  = test_df[target_col_b].values.astype("float32")

print("Train:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

Train: (2741, 15) Val: (588, 15) Test: (588, 15)

In [58]:
from sklearn.preprocessing import StandardScaler

scaler_b = StandardScaler()
X_train_scaled = scaler_b.fit_transform(X_train)
X_val_scaled   = scaler_b.transform(X_val)
X_test_scaled  = scaler_b.transform(X_test)

In [59]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

def build_mlp_model(input_dim):
    model = tf.keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(32, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(1)  # regresión
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="mse",
        metrics=["mae"]
    )
    return model

input_dim = X_train_scaled.shape[1]
mlp_model = build_mlp_model(input_dim)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

history = mlp_model.fit(
    X_train_scaled, y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=200,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10058.0605 - mae: 99.3362 - val_loss: 8062.0215 - val_mae: 88.5692
Epoch 2/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5487.6089 - mae: 70.3306 - val_loss: 1795.4624 - val_mae: 37.0665
Epoch 3/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1613.0992 - mae: 33.7391 - val_loss: 924.1995 - val_mae: 24.3680
Epoch 4/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1144.9077 - mae: 27.3543 - val_loss: 651.2697 - val_mae: 20.4190
Epoch 5/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 914.0450 - mae: 24.4025 - val_loss: 566.6995 - val_mae: 18.6874
Epoch 6/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 818.3356 - mae: 22.7331 - val_loss: 442.8829 - val_mae: 16.6680
Epoch 7/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 747.4603 - mae: 21.7674 - val_loss: 397.0466 - val_mae: 15.8324
Epoch 8/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 724.7413 - mae: 21.1555 - val_loss: 347.3976 - val_mae: 14.8124
Epoch 9/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 673.0684 - mae: 20.5060 - val_loss: 331.4315 - val_mae: 14.4060
Epoch 10/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 635.6614 - mae: 20.0712 - val_loss: 309.2066 - val_mae: 13.8920
Epoch 11/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 615.7166 - mae: 19.8582 - val_loss: 290.5265 - val_mae: 13.4556
Epoch 12/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 604.6927 - mae: 19.5805 - val_loss: 273.1835 - val_mae: 13.0862
Epoch 13/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 580.0544 - mae: 19.2213 - val_loss: 267.8307 - val_mae: 12.9407
Epoch 14/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 583.2429 - mae: 19.3458 - val_loss: 246.9716 - val_mae: 12.4323
Epoch 15/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 557.5836 - mae: 18.9436 - val_loss: 248.2785 - val_mae: 12.3751
Epoch 16/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 543.7833 - mae: 18.6077 - val_loss: 249.3544 - val_mae: 12.3668
Epoch 17/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 544.0189 - mae: 18.6232 - val_loss: 237.0787 - val_mae: 12.0564
Epoch 18/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 563.1798 - mae: 19.0267 - val_loss: 226.0166 - val_mae: 11.9066
Epoch 19/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 525.0313 - mae: 18.3546 - val_loss: 223.7064 - val_mae: 11.8044
Epoch 20/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 524.1839 - mae: 18.2576 - val_loss: 214.3085 - val_mae: 11.5870
Epoch 21/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 500.3861 - mae: 17.7755 - val_loss: 218.6185 - val_mae: 11.6290
Epoch 22/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 535.2764 - mae: 18.4337 - val_loss: 206.2297 - val_mae: 11.3793
Epoch 23/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 516.0486 - mae: 18.1459 - val_loss: 206.1290 - val_mae: 11.3143
Epoch 24/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 508.7801 - mae: 18.0093 - val_loss: 215.1971 - val_mae: 11.5446
Epoch 25/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 511.3445 - mae: 18.0420 - val_loss: 208.7198 - val_mae: 11.3866
Epoch 26/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 492.0976 - mae: 17.7101 - val_loss: 196.1293 - val_mae: 11.1139
Epoch 27/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 497.3248 - mae: 17.7669 - val_loss: 202.8773 - val_mae: 11.2391
Epoch 28/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 486.8102 - mae: 17.6897 - val_loss: 201.8842 - val_mae: 11.3011
Epoch 29/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 481.0953 - mae: 17.4655 - val_loss: 201.5516 - val_mae: 11.2247
Epoch 30/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 501.1119 - mae: 17.8502 - val_loss: 195.0715 - val_mae: 11.0694
Epoch 31/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 478.7725 - mae: 17.5554 - val_loss: 192.6867 - val_mae: 11.0754
Epoch 32/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 483.3683 - mae: 17.6824 - val_loss: 194.6042 - val_mae: 10.9882
Epoch 33/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 461.5507 - mae: 17.2181 - val_loss: 190.4581 - val_mae: 10.9147
Epoch 34/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 472.0330 - mae: 17.4144 - val_loss: 184.4924 - val_mae: 10.7421
Epoch 35/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 466.1333 - mae: 17.0306 - val_loss: 178.0845 - val_mae: 10.6252
Epoch 36/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 487.8188 - mae: 17.6556 - val_loss: 184.5801 - val_mae: 10.8102
Epoch 37/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 481.4785 - mae: 17.5406 - val_loss: 183.2395 - val_mae: 10.7647
Epoch 38/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 455.4374 - mae: 17.1764 - val_loss: 194.5848 - val_mae: 11.1245
Epoch 39/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 464.0159 - mae: 17.3141 - val_loss: 181.5098 - val_mae: 10.7163
Epoch 40/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 471.9053 - mae: 17.3885 - val_loss: 180.8143 - val_mae: 10.6367
Epoch 41/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 476.8586 - mae: 17.4403 - val_loss: 188.3185 - val_mae: 10.8176
Epoch 42/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 462.5613 - mae: 16.7630 - val_loss: 177.5484 - val_mae: 10.5487
Epoch 43/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 453.5799 - mae: 17.0236 - val_loss: 181.6293 - val_mae: 10.6352
Epoch 44/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 477.3589 - mae: 17.5348 - val_loss: 173.5543 - val_mae: 10.5235
Epoch 45/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 448.8444 - mae: 16.9721 - val_loss: 178.6066 - val_mae: 10.6060
Epoch 46/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 451.1741 - mae: 16.7734 - val_loss: 179.1385 - val_mae: 10.6250
Epoch 47/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 444.3716 - mae: 16.7490 - val_loss: 184.5699 - val_mae: 10.8533
Epoch 48/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 459.7838 - mae: 16.9648 - val_loss: 181.6486 - val_mae: 10.7061
Epoch 49/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 460.9554 - mae: 17.0976 - val_loss: 178.4218 - val_mae: 10.6283
Epoch 50/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 440.1100 - mae: 16.7344 - val_loss: 174.8805 - val_mae: 10.4844
Epoch 51/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 431.6583 - mae: 16.5039 - val_loss: 177.1695 - val_mae: 10.6348
Epoch 52/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 457.5826 - mae: 17.0349 - val_loss: 173.3373 - val_mae: 10.4532
Epoch 53/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 445.7799 - mae: 16.9561 - val_loss: 172.9715 - val_mae: 10.4803
Epoch 54/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 447.3411 - mae: 16.9420 - val_loss: 171.7903 - val_mae: 10.3754
Epoch 55/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 481.5530 - mae: 17.4194 - val_loss: 180.4131 - val_mae: 10.6535
Epoch 56/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 426.8979 - mae: 16.5088 - val_loss: 173.2191 - val_mae: 10.4796
Epoch 57/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 440.0058 - mae: 16.8001 - val_loss: 185.3796 - val_mae: 10.9712
Epoch 58/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 453.0417 - mae: 17.0648 - val_loss: 180.2457 - val_mae: 10.7525
Epoch 59/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 430.8393 - mae: 16.6016 - val_loss: 177.3317 - val_mae: 10.5895
Epoch 60/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 430.2269 - mae: 16.6230 - val_loss: 172.5256 - val_mae: 10.4441
Epoch 61/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438.7008 - mae: 16.7598 - val_loss: 171.9974 - val_mae: 10.4519
Epoch 62/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 447.9703 - mae: 16.8474 - val_loss: 170.9991 - val_mae: 10.4270
Epoch 63/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 424.2527 - mae: 16.4487 - val_loss: 199.0927 - val_mae: 11.3884
Epoch 64/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 431.5221 - mae: 16.5919 - val_loss: 171.3660 - val_mae: 10.4690
Epoch 65/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 448.8304 - mae: 17.1215 - val_loss: 186.9722 - val_mae: 10.9166
Epoch 66/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 432.5280 - mae: 16.6714 - val_loss: 178.3049 - val_mae: 10.5834
Epoch 67/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 430.5504 - mae: 16.6344 - val_loss: 175.0612 - val_mae: 10.4436
Epoch 68/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 427.8818 - mae: 16.4805 - val_loss: 173.3796 - val_mae: 10.4934
Epoch 69/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 424.6086 - mae: 16.4543 - val_loss: 188.3630 - val_mae: 10.9821
Epoch 70/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 437.3293 - mae: 16.6568 - val_loss: 173.6140 - val_mae: 10.5103
Epoch 71/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 426.5764 - mae: 16.4001 - val_loss: 182.3677 - val_mae: 10.7242
Epoch 72/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 428.4013 - mae: 16.4502 - val_loss: 177.0608 - val_mae: 10.6411

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Evaluación directa de Keras
test_loss, test_mae = mlp_model.evaluate(X_test_scaled, y_test, verbose=0)
print("MLP - test MSE (Keras):", test_loss)
print("MLP - test MAE (Keras):", test_mae)

# Métricas más completas
y_pred = mlp_model.predict(X_test_scaled).flatten()

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2  = r2_score(y_test, y_pred)

print("\nMLP - MAE:", mae)
print("MLP - MSE:", mse)
print("MLP - R² :", r2)

# Baseline media para comparar
y_mean = np.mean(y_test)
baseline_pred = np.full_like(y_test, y_mean)

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_mse = mean_squared_error(y_test, baseline_pred)
baseline_r2  = r2_score(y_test, baseline_pred)

print("\nBaseline MAE:", baseline_mae)
print("Baseline MSE:", baseline_mse)
print("Baseline R² :", baseline_r2)

MLP - test MSE (Keras): 203.68870544433594
MLP - test MAE (Keras): 11.384740829467773
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

MLP - MAE: 11.384740829467773
MLP - MSE: 203.68869018554688
MLP - R² : -0.03834092617034912

Baseline MAE: 11.024249076843262
Baseline MSE: 196.16746520996094
Baseline R² : 0.0

In [ ]:
import mlflow
import mlflow.keras  # o mlflow.tensorflow según tu versión

mlflow.set_experiment("nba_lakers_mlp_tabular")

with mlflow.start_run(run_name="mlp_tabular_roll5"):
    mlflow.log_param("model_type", "MLP_tabular")
    mlflow.log_param("window", window)
    mlflow.log_param("hidden_layers", [64, 32])
    mlflow.log_param("dropout", 0.3)
    mlflow.log_param("optimizer", "adam")
    mlflow.log_param("learning_rate", 1e-3)
    mlflow.log_metric("test_mae", float(mae))
    mlflow.log_metric("test_mse", float(mse))
    mlflow.log_metric("test_r2", float(r2))
    
    # Guardar el modelo
    mlflow.keras.log_model(mlp_model, artifact_path="mlp_model")

In [61]:
df_lakers_opp.head()

,SEASON_ID,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,ES_CASA,OPONENTE,WIN,DAYS_REST,OPP_MIN,OPP_PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_OPP_WIN
0,21983,0028300010,1983-10-29,LAL @ UTH,W,240,120,46,98,0.469,0,1,0.000,28,39,0.718,29,31,60,25,10,10,20,41,0,UTA,1,2,240,115,35,77,0.455,1,3,0.333,44,60,0.733,15,26,41,21,8,10,17,27,0
1,21983,0028300035,1983-11-02,LAL @ SDC,L,240,106,43,96,0.448,1,2,0.500,19,25,0.760,16,33,49,29,14,7,24,24,0,LAC,0,4,240,110,47,91,0.516,0,1,0.000,16,23,0.696,11,31,42,30,12,8,20,24,1
2,21983,0028300053,1983-11-05,LAL @ DAL,L,240,102,47,97,0.485,0,2,0.000,8,12,0.667,18,23,41,29,7,8,20,27,0,DAL,0,3,240,107,43,97,0.443,0,2,0.000,21,26,0.808,22,26,48,26,9,4,16,20,1
3,21983,0028300066,1983-11-08,LAL @ DEN,W,240,133,49,106,0.462,2,3,0.667,33,36,0.917,22,31,53,30,11,8,23,31,0,DEN,1,3,240,124,44,96,0.458,0,8,0.000,36,42,0.857,14,30,44,28,15,4,24,26,0
4,21983,0028300068,1983-11-09,LAL vs. DAL,W,240,120,50,94,0.532,2,3,0.667,18,28,0.643,16,33,49,33,7,6,17,31,1,DAL,1,1,240,106,34,83,0.410,0,2,0.000,38,46,0.826,13,30,43,22,7,2,18,23,0

## Nuevo engeneering de features

In [62]:
import numpy as np
import pandas as pd

df = df_lakers_opp.copy()

# Asegurar orden temporal
df = df.sort_values("GAME_DATE").reset_index(drop=True)

# -----------------------------
# Posesiones estimadas Lakers y rival
# -----------------------------
# Ajusta nombres si en tu df son distintos
lal_poss = (
    df["FGA"]
    + 0.44 * df["FTA"]
    - df["OREB"]
    + df["TOV"]
)

opp_poss = (
    df["OPP_FGA"]
    + 0.44 * df["OPP_FTA"]
    - df["OPP_OREB"]
    + df["OPP_TOV"]
)

# Posesiones del partido ≈ media de las dos estimaciones
df["POSS_EST"] = (lal_poss + opp_poss) / 2

# Evitar divisiones raras
df = df[df["POSS_EST"] > 0].reset_index(drop=True)

# -----------------------------
# Ratings avanzados por partido
# -----------------------------
df["LAL_OFF_RTG"] = 100 * df["PTS"] / df["POSS_EST"]
df["LAL_DEF_RTG"] = 100 * df["OPP_PTS"] / df["POSS_EST"]
df["LAL_NET_RTG"] = df["LAL_OFF_RTG"] - df["LAL_DEF_RTG"]

df["OPP_OFF_RTG"] = 100 * df["OPP_PTS"] / df["POSS_EST"]
df["OPP_DEF_RTG"] = 100 * df["PTS"] / df["POSS_EST"]
df["OPP_NET_RTG"] = df["OPP_OFF_RTG"] - df["OPP_DEF_RTG"]

df[["GAME_DATE", "PTS", "OPP_PTS", "LAL_OFF_RTG", "LAL_DEF_RTG", "OPP_OFF_RTG", "OPP_DEF_RTG"]].head()

   GAME_DATE  PTS  OPP_PTS  LAL_OFF_RTG  LAL_DEF_RTG  OPP_OFF_RTG  OPP_DEF_RTG
0 1983-10-29  120      115   113.442995   108.716203   108.716203   113.442995
1 1983-11-02  106      110    94.171997    97.725657    97.725657    94.171997
2 1983-11-05  102      107    98.684211   103.521672   103.521672    98.684211
3 1983-11-08  133      124   107.552968   100.274947   100.274947   107.552968
4 1983-11-09  120      106   111.337911    98.348488    98.348488   111.337911

In [63]:
window = 5  # partidos recientes

# Stats base Lakers / rival
lakers_base_cols = ["PTS", "FG_PCT", "FG3_PCT", "REB", "AST"]
opp_base_cols    = ["OPP_PTS", "OPP_FG_PCT", "OPP_FG3_PCT", "OPP_REB", "OPP_AST"]

# Rolling de stats simples
for col in lakers_base_cols:
    df[f"LAL_{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

for col in opp_base_cols:
    df[f"{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

# Rolling de ratings avanzados
rating_cols_lal = ["LAL_OFF_RTG", "LAL_DEF_RTG", "LAL_NET_RTG"]
rating_cols_opp = ["OPP_OFF_RTG", "OPP_DEF_RTG", "OPP_NET_RTG"]

for col in rating_cols_lal:
    df[f"{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

for col in rating_cols_opp:
    df[f"{col}_roll{window}"] = (
        df[col].rolling(window=window, min_periods=window).mean().shift(1)
    )

In [65]:
def compute_streak(series_win):
    streaks = []
    streak = 0
    for w in series_win:
        if w == 1:
            streak += 1
        else:
            streak = 0
        streaks.append(streak)
    # shift(1): racha *antes* del partido
    return pd.Series(streaks).shift(1)

# Asegúrate de que WIN y OPP_WIN sean 0/1
df["LAL_WIN_STREAK"] = compute_streak(df["WIN"])
df["OPP_WIN_STREAK"] = compute_streak(df["OPP_OPP_WIN"])

In [66]:
# B2B si DAYS_REST == 0
df["LAL_B2B"] = (df["DAYS_REST"] == 0).astype(int)

# Si no tienes DAYS_REST del rival, puedes omitir OPP_B2B
# Si lo tuvieras como OPP_DAYS_REST:
# df["OPP_B2B"] = (df["OPP_DAYS_REST"] == 0).astype(int)

In [67]:
feature_cols_b = [
    # Contexto básico
    "ES_CASA",
    "DAYS_REST",
    "LAL_B2B",
    
    # Forma reciente Lakers (rolling stats)
    f"LAL_PTS_roll{window}",
    f"LAL_FG_PCT_roll{window}",
    f"LAL_FG3_PCT_roll{window}",
    f"LAL_REB_roll{window}",
    f"LAL_AST_roll{window}",
    "LAL_WIN_STREAK",
    
    # Forma reciente rival
    f"OPP_PTS_roll{window}",
    f"OPP_FG_PCT_roll{window}",
    f"OPP_FG3_PCT_roll{window}",
    f"OPP_REB_roll{window}",
    f"OPP_AST_roll{window}",
    "OPP_WIN_STREAK",
    
    # Ratings avanzados (forma reciente, no partido puntual)
    f"LAL_OFF_RTG_roll{window}",
    f"LAL_DEF_RTG_roll{window}",
    f"LAL_NET_RTG_roll{window}",
    f"OPP_OFF_RTG_roll{window}",
    f"OPP_DEF_RTG_roll{window}",
    f"OPP_NET_RTG_roll{window}",
]

target_col_b = "PTS"

# Quitamos filas donde falte algo (por los rollings/streaks)
df_model = df.dropna(subset=feature_cols_b + [target_col_b]).reset_index(drop=True)

print("Shape df_model_ext:", df_model.shape)

Shape df_model_ext: (3917, 74)

In [68]:
from sklearn.preprocessing import StandardScaler

# Split temporal 70 / 15 / 15
n = len(df_model)
train_end = int(n * 0.7)
val_end   = int(n * 0.85)

train_df = df_model.iloc[:train_end]
val_df   = df_model.iloc[train_end:val_end]
test_df  = df_model.iloc[val_end:]

X_train = train_df[feature_cols_b].values.astype("float32")
y_train = train_df[target_col_b].values.astype("float32")

X_val   = val_df[feature_cols_b].values.astype("float32")
y_val   = val_df[target_col_b].values.astype("float32")

X_test  = test_df[feature_cols_b].values.astype("float32")
y_test  = test_df[target_col_b].values.astype("float32")

print("Train:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

# Escalado
scaler_b = StandardScaler()
X_train_scaled = scaler_b.fit_transform(X_train)
X_val_scaled   = scaler_b.transform(X_val)
X_test_scaled  = scaler_b.transform(X_test)

Train: (2741, 21) Val: (588, 21) Test: (588, 21)

In [69]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping

def build_mlp_model(input_dim):
    model = tf.keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.4),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.4),
        layers.Dense(1)  # regresión
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=3e-4),
        loss="mse",
        metrics=["mae"]
    )
    return model

input_dim = X_train_scaled.shape[1]
mlp_model = build_mlp_model(input_dim)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=12,
    restore_best_weights=True
)

history = mlp_model.fit(
    X_train_scaled, y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=200,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 10656.2744 - mae: 102.3566 - val_loss: 9977.4512 - val_mae: 98.8975
Epoch 2/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9510.4521 - mae: 96.5571 - val_loss: 7875.4551 - val_mae: 87.3328
Epoch 3/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7039.9009 - mae: 82.0831 - val_loss: 4465.3325 - val_mae: 62.7945
Epoch 4/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4007.6833 - mae: 58.8469 - val_loss: 2068.6145 - val_mae: 39.0501
Epoch 5/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2209.3936 - mae: 40.8473 - val_loss: 1710.4573 - val_mae: 34.6649
Epoch 6/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1810.7462 - mae: 35.5022 - val_loss: 1626.9677 - val_mae: 33.2366
Epoch 7/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1659.4417 - mae: 33.6579 - val_loss: 1477.2283 - val_mae: 31.5790
Epoch 8/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1475.9285 - mae: 31.5497 - val_loss: 1324.9570 - val_mae: 29.6896
Epoch 9/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1336.7952 - mae: 29.9377 - val_loss: 1228.0306 - val_mae: 28.4244
Epoch 10/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1278.7838 - mae: 29.1211 - val_loss: 1083.4470 - val_mae: 26.6509
Epoch 11/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1123.1853 - mae: 26.9658 - val_loss: 967.2708 - val_mae: 25.1753
Epoch 12/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1030.9923 - mae: 26.0328 - val_loss: 864.3770 - val_mae: 23.7381
Epoch 13/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 903.9263 - mae: 24.2813 - val_loss: 757.1809 - val_mae: 22.0961
Epoch 14/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 894.3221 - mae: 24.0814 - val_loss: 684.2511 - val_mae: 20.9724
Epoch 15/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 906.6520 - mae: 24.2910 - val_loss: 628.8094 - val_mae: 20.1033
Epoch 16/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 782.3984 - mae: 22.4205 - val_loss: 575.0714 - val_mae: 19.1762
Epoch 17/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 768.3391 - mae: 21.9576 - val_loss: 525.0093 - val_mae: 18.3285
Epoch 18/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 760.5284 - mae: 21.9605 - val_loss: 491.2346 - val_mae: 17.6895
Epoch 19/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 700.4256 - mae: 21.3676 - val_loss: 454.0194 - val_mae: 16.9579
Epoch 20/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 661.2300 - mae: 20.6756 - val_loss: 438.1601 - val_mae: 16.6490
Epoch 21/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 683.1992 - mae: 20.9504 - val_loss: 397.6242 - val_mae: 15.8712
Epoch 22/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 659.9266 - mae: 20.3007 - val_loss: 376.4355 - val_mae: 15.4361
Epoch 23/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 631.7291 - mae: 20.2462 - val_loss: 355.6013 - val_mae: 14.9934
Epoch 24/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 599.2200 - mae: 19.8179 - val_loss: 333.5560 - val_mae: 14.4661
Epoch 25/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 579.6951 - mae: 19.0863 - val_loss: 326.6448 - val_mae: 14.2972
Epoch 26/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 624.7766 - mae: 20.0876 - val_loss: 320.4585 - val_mae: 14.1934
Epoch 27/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 598.2815 - mae: 19.5270 - val_loss: 304.2451 - val_mae: 13.8264
Epoch 28/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 557.2297 - mae: 19.0591 - val_loss: 293.5078 - val_mae: 13.5169
Epoch 29/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 578.9365 - mae: 19.1706 - val_loss: 282.0661 - val_mae: 13.2547
Epoch 30/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 566.4343 - mae: 18.9758 - val_loss: 278.1078 - val_mae: 13.1523
Epoch 31/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 566.3027 - mae: 18.9315 - val_loss: 271.5921 - val_mae: 12.9721
Epoch 32/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 544.5223 - mae: 18.5945 - val_loss: 267.3309 - val_mae: 12.8963
Epoch 33/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 547.1220 - mae: 18.5157 - val_loss: 260.9249 - val_mae: 12.7035
Epoch 34/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 571.8139 - mae: 19.0184 - val_loss: 258.7118 - val_mae: 12.6584
Epoch 35/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 519.7593 - mae: 18.1565 - val_loss: 252.8857 - val_mae: 12.5008
Epoch 36/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 521.4286 - mae: 18.2474 - val_loss: 242.7878 - val_mae: 12.2670
Epoch 37/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 529.9401 - mae: 18.3414 - val_loss: 234.8812 - val_mae: 12.0709
Epoch 38/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 522.2923 - mae: 18.3666 - val_loss: 236.3952 - val_mae: 12.0574
Epoch 39/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 518.1446 - mae: 18.2269 - val_loss: 228.3275 - val_mae: 11.8820
Epoch 40/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 530.3616 - mae: 18.4041 - val_loss: 225.4567 - val_mae: 11.7716
Epoch 41/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 498.1307 - mae: 17.8655 - val_loss: 227.1510 - val_mae: 11.8428
Epoch 42/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 481.6664 - mae: 17.5010 - val_loss: 220.6391 - val_mae: 11.7225
Epoch 43/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 483.5574 - mae: 17.5712 - val_loss: 224.9278 - val_mae: 11.7779
Epoch 44/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 477.4392 - mae: 17.4329 - val_loss: 220.2398 - val_mae: 11.6772
Epoch 45/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 497.8930 - mae: 17.8264 - val_loss: 216.1245 - val_mae: 11.5402
Epoch 46/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 487.9158 - mae: 17.5927 - val_loss: 218.4668 - val_mae: 11.6000
Epoch 47/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 460.3037 - mae: 17.1192 - val_loss: 208.3889 - val_mae: 11.3014
Epoch 48/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 461.4080 - mae: 17.0331 - val_loss: 214.3992 - val_mae: 11.5858
Epoch 49/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 487.1115 - mae: 17.5428 - val_loss: 207.9978 - val_mae: 11.3003
Epoch 50/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 484.4007 - mae: 17.4895 - val_loss: 203.6448 - val_mae: 11.2321
Epoch 51/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 467.9085 - mae: 17.3897 - val_loss: 201.0390 - val_mae: 11.1535
Epoch 52/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 476.8416 - mae: 17.4061 - val_loss: 204.1150 - val_mae: 11.2486
Epoch 53/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 454.4874 - mae: 16.9841 - val_loss: 204.0342 - val_mae: 11.2203
Epoch 54/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 483.4927 - mae: 17.5658 - val_loss: 200.9127 - val_mae: 11.1447
Epoch 55/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 459.3542 - mae: 16.9936 - val_loss: 199.2467 - val_mae: 11.1251
Epoch 56/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 447.8275 - mae: 16.8640 - val_loss: 201.9853 - val_mae: 11.1723
Epoch 57/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 487.9655 - mae: 17.6334 - val_loss: 200.7060 - val_mae: 11.2197
Epoch 58/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 467.1717 - mae: 17.0583 - val_loss: 196.9099 - val_mae: 11.0407
Epoch 59/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 455.1479 - mae: 17.0076 - val_loss: 194.3814 - val_mae: 10.9715
Epoch 60/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 478.3838 - mae: 17.5387 - val_loss: 195.9287 - val_mae: 11.0901
Epoch 61/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 473.5795 - mae: 17.3945 - val_loss: 195.0541 - val_mae: 10.9836
Epoch 62/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 454.2289 - mae: 17.0433 - val_loss: 190.3835 - val_mae: 10.8988
Epoch 63/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 459.5064 - mae: 17.1164 - val_loss: 194.6885 - val_mae: 11.0964
Epoch 64/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 440.8291 - mae: 16.7940 - val_loss: 185.1914 - val_mae: 10.7983
Epoch 65/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 450.3742 - mae: 16.9701 - val_loss: 196.8189 - val_mae: 11.0314
Epoch 66/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 468.0474 - mae: 17.1661 - val_loss: 188.9724 - val_mae: 10.8759
Epoch 67/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 442.5173 - mae: 16.8005 - val_loss: 186.6446 - val_mae: 10.8929
Epoch 68/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 441.5310 - mae: 16.6086 - val_loss: 184.6560 - val_mae: 10.7944
Epoch 69/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 455.8987 - mae: 16.8947 - val_loss: 182.7068 - val_mae: 10.7482
Epoch 70/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 449.7072 - mae: 16.9955 - val_loss: 182.9575 - val_mae: 10.7360
Epoch 71/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 461.2123 - mae: 17.1167 - val_loss: 186.3889 - val_mae: 10.8195
Epoch 72/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 472.8539 - mae: 17.4285 - val_loss: 185.5178 - val_mae: 10.8508
Epoch 73/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 466.2517 - mae: 17.1993 - val_loss: 181.7439 - val_mae: 10.6399
Epoch 74/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 447.4245 - mae: 16.9727 - val_loss: 182.8503 - val_mae: 10.7427
Epoch 75/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 425.4265 - mae: 16.3730 - val_loss: 189.2436 - val_mae: 10.8203
Epoch 76/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438.8144 - mae: 16.5922 - val_loss: 187.7896 - val_mae: 10.9506
Epoch 77/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 428.5198 - mae: 16.5275 - val_loss: 184.0660 - val_mae: 10.7709
Epoch 78/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 442.3210 - mae: 16.9138 - val_loss: 185.5894 - val_mae: 10.7389
Epoch 79/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 444.1331 - mae: 16.8346 - val_loss: 183.7279 - val_mae: 10.7857
Epoch 80/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 452.2705 - mae: 16.9978 - val_loss: 185.2816 - val_mae: 10.8433
Epoch 81/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 443.5240 - mae: 16.7118 - val_loss: 183.6956 - val_mae: 10.7263
Epoch 82/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 427.6781 - mae: 16.7429 - val_loss: 178.4653 - val_mae: 10.5711
Epoch 83/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 428.6357 - mae: 16.6291 - val_loss: 178.9022 - val_mae: 10.6012
Epoch 84/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 437.3973 - mae: 16.6105 - val_loss: 183.8215 - val_mae: 10.7864
Epoch 85/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 432.1712 - mae: 16.6444 - val_loss: 183.8706 - val_mae: 10.7753
Epoch 86/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 412.5016 - mae: 16.1826 - val_loss: 177.0562 - val_mae: 10.6192
Epoch 87/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 415.4825 - mae: 16.1159 - val_loss: 178.3775 - val_mae: 10.6638
Epoch 88/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 427.9226 - mae: 16.6127 - val_loss: 176.2582 - val_mae: 10.5257
Epoch 89/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 434.3355 - mae: 16.6697 - val_loss: 177.2008 - val_mae: 10.6122
Epoch 90/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 434.2379 - mae: 16.6726 - val_loss: 176.7709 - val_mae: 10.5856
Epoch 91/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 431.2195 - mae: 16.7139 - val_loss: 173.9172 - val_mae: 10.4902
Epoch 92/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 398.3854 - mae: 16.0944 - val_loss: 175.2372 - val_mae: 10.5263
Epoch 93/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 427.3211 - mae: 16.4806 - val_loss: 178.4063 - val_mae: 10.6563
Epoch 94/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 428.5828 - mae: 16.5651 - val_loss: 174.5075 - val_mae: 10.5046
Epoch 95/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 412.7503 - mae: 16.1501 - val_loss: 175.3875 - val_mae: 10.5030
Epoch 96/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 437.4102 - mae: 16.7132 - val_loss: 173.6590 - val_mae: 10.4579
Epoch 97/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 441.6999 - mae: 16.8642 - val_loss: 181.8354 - val_mae: 10.7400
Epoch 98/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 416.5075 - mae: 16.4650 - val_loss: 173.6761 - val_mae: 10.4353
Epoch 99/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 425.6591 - mae: 16.4537 - val_loss: 175.1924 - val_mae: 10.4942
Epoch 100/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 415.2086 - mae: 16.3223 - val_loss: 172.6936 - val_mae: 10.4445
Epoch 101/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 424.8573 - mae: 16.3946 - val_loss: 171.8165 - val_mae: 10.4755
Epoch 102/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 438.3506 - mae: 16.6878 - val_loss: 175.2627 - val_mae: 10.4640
Epoch 103/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 412.3050 - mae: 16.2186 - val_loss: 169.3559 - val_mae: 10.3504
Epoch 104/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 410.9264 - mae: 16.0735 - val_loss: 173.5836 - val_mae: 10.4930
Epoch 105/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 429.5179 - mae: 16.5679 - val_loss: 173.5759 - val_mae: 10.5405
Epoch 106/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 416.8531 - mae: 16.1491 - val_loss: 176.6975 - val_mae: 10.5460
Epoch 107/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 422.3938 - mae: 16.3759 - val_loss: 173.2157 - val_mae: 10.4250
Epoch 108/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 412.7061 - mae: 16.2232 - val_loss: 176.0917 - val_mae: 10.5530
Epoch 109/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 434.4999 - mae: 16.6051 - val_loss: 179.7641 - val_mae: 10.5344
Epoch 110/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 433.8048 - mae: 16.6495 - val_loss: 175.6451 - val_mae: 10.5555
Epoch 111/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 409.9807 - mae: 16.1678 - val_loss: 175.2239 - val_mae: 10.4862
Epoch 112/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 426.9943 - mae: 16.6266 - val_loss: 172.3966 - val_mae: 10.4370
Epoch 113/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 418.3979 - mae: 16.3966 - val_loss: 172.6982 - val_mae: 10.4054
Epoch 114/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 430.4900 - mae: 16.5408 - val_loss: 172.1037 - val_mae: 10.5044
Epoch 115/200
86/86 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 422.5480 - mae: 16.4331 - val_loss: 172.4345 - val_mae: 10.4021

In [70]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Evaluación Keras
test_loss, test_mae = mlp_model.evaluate(X_test_scaled, y_test, verbose=0)
print("MLP - test MSE (Keras):", test_loss)
print("MLP - test MAE (Keras):", test_mae)

# Métricas detalladas
y_pred = mlp_model.predict(X_test_scaled).flatten()

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2  = r2_score(y_test, y_pred)

print("\nMLP avanzado - MAE:", mae)
print("MLP avanzado - MSE:", mse)
print("MLP avanzado - R² :", r2)

# Baseline media
y_mean = np.mean(y_test)
baseline_pred = np.full_like(y_test, y_mean)

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_mse = mean_squared_error(y_test, baseline_pred)
baseline_r2  = r2_score(y_test, baseline_pred)

print("\nBaseline MAE:", baseline_mae)
print("Baseline MSE:", baseline_mse)
print("Baseline R² :", baseline_r2)

MLP - test MSE (Keras): 206.6910400390625
MLP - test MAE (Keras): 11.507651329040527
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

MLP avanzado - MAE: 11.507651329040527
MLP avanzado - MSE: 206.69100952148438
MLP avanzado - R² : -0.05364573001861572

Baseline MAE: 11.024249076843262
Baseline MSE: 196.16746520996094
Baseline R² : 0.0